version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: shopsmart-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secureMongoPass123
    networks:
      - shopsmart-network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: shopsmart-redis
    command: redis-server --requirepass secureRedisPass123
    networks:
      - shopsmart-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:secureMongoPass123@mongodb:27017/users?authSource=admin
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongodb
    networks:
      - shopsmart-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:secureMongoPass123@mongodb:27017/inventory?authSource=admin
    depends_on:
      - mongodb
    networks:
      - shopsmart-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:secureMongoPass123@mongodb:27017/orders?authSource=admin
    depends_on:
      - mongodb
    networks:
      - shopsmart-network

networks:
  shopsmart-network:
    driver: bridge

volumes:
  mongodb_data: