spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:secureMongoPass123@shopsmart-mongodb:27017/users?authSource=admin}
  
# MySQL config hatao ya comment karo:
# spring:
#   datasource:
#     url: jdbc:mysql://mysql-db:3306/userdb
#     username: root
#     password: password
#   jpa:
#     hibernate:
#       ddl-auto: update