apiVersion: v1
kind: Secret
metadata:
  name: shopsmart-secrets
  namespace: shopsmart
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  JWT_SECRET: "shopsmart-secret-key-change-in-prod-12345"
  STRIPE_SECRET_KEY: "sk_test_your_stripe_key_here"